/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Kasir;

import javax.swing.table.DefaultTableModel;
import database.Koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Putra
 */
public class invoice extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    private DefaultTableModel tabmode;
    private JMenuBar menuBar; 
    private JMenu menu; 
    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(560, 590); 
        this.setResizable(true);
        con = new Koneksi().connect();
        menuBar = new JMenuBar(); 
    menu = new JMenu("Menu"); 

JMenuItem menuItemFrom_Login = new JMenuItem("Logout");
menuItemFrom_Login.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        dispose(); 
        new Login.From_Login().setVisible(true); 
    }
});

menu.add(menuItemFrom_Login);
menuBar.add(menu);
setJMenuBar(menuBar);
        
    }
    
    protected void datatable() {
        Object[] Baris = {"ID Transaksi", "Total Harga", "Uang Customer", "Kembalian"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_invoice.setModel(tabmode);
        String sql = "SELECT * FROM invoice ORDER BY id_transaksi ASC";
        try {
            Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String idtransaksi = hasil.getString("id_transaksi");
                String totalharga = hasil.getString("totalharga");
                String uangcash = hasil.getString("uangcash");
                String kembalian = hasil.getString("kembalian");

                String[] data = {idtransaksi, totalharga, uangcash, kembalian};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    
    protected void dataterpilih() {
    int bar = tb_invoice.getSelectedRow();
    String idtransaksi = tabmode.getValueAt(bar, 0).toString();
    String total = tabmode.getValueAt(bar, 1).toString();
    String uang = tabmode.getValueAt(bar, 2).toString();
    String kembali = tabmode.getValueAt(bar, 3).toString();

    id_transaksi.setText(idtransaksi);
    totalharga.setText(total);
    uangcash.setText(uang);
    kembalian.setText(kembali);
}

    
    protected void cari() {
    Object[] Baris = {"ID Transaksi", "Total Harga", "Uang Customer", "Kembalian"};
    tabmode = new DefaultTableModel(null, Baris);
    tb_invoice.setModel(tabmode);
    String keyword = cari.getText();
    String sql = "SELECT * FROM invoice WHERE id_transaksi LIKE '%" + keyword + "%' ORDER BY id_transaksi ASC";

    try {
        Statement stat = con.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            String a = hasil.getString("id_transaksi");
            String b = hasil.getString("totalharga");
            String c = hasil.getString("uangcash");
            String d = hasil.getString("kembalian");

            String[] data = {a, b, c, d};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        System.err.println("Cari Error : " + e.getMessage());
    }
}

        
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_invoice = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        uangcash = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Data Transaksi");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 520, 70);
        jPanel1.add(cari);
        cari.setBounds(180, 100, 220, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 100, 100, 30);

        tb_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_invoiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_invoice);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 510, 94);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID Transaksi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 280, 170, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Total Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 320, 170, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Uang Customer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 360, 180, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Uang Kembalian");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 400, 170, 30);
        jPanel1.add(id_transaksi);
        id_transaksi.setBounds(210, 280, 284, 30);

        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        jPanel1.add(totalharga);
        totalharga.setBounds(210, 320, 284, 30);
        jPanel1.add(uangcash);
        uangcash.setBounds(210, 360, 284, 30);
        jPanel1.add(kembalian);
        kembalian.setBounds(210, 400, 284, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Tampilkan Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(344, 460, 119, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ChatGPT Image Jun 23, 2025, 10_27_41 PM.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-80, 0, 1030, 780);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Logout");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void tb_invoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_invoiceMouseClicked
        // TODO add your handling code here:
        dataterpilih();
    }//GEN-LAST:event_tb_invoiceMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTable tb_invoice;
    private javax.swing.JTextField totalharga;
    private javax.swing.JTextField uangcash;
    // End of variables declaration//GEN-END:variables
}
