/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Owner;

import Admin.stok_barang;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import database.Koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Admin.create_user;
/**
 *
 * @author Putra
 */
public class Penghasilan extends javax.swing.JFrame {

    Connection con;
    Statement stm;
    ResultSet rs;
    private DefaultTableModel tabmode;
    private JMenuBar menuBar; 
    private JMenu menu; 
    /**
     * Creates new form Penghasilan
     */
    public Penghasilan() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(550, 650); 
        this.setResizable(true);
        con = new Koneksi().connect();
    System.out.println("Connection: " + con);
    System.out.println("tb_invoice: " + tb_invoice);
    System.out.println("totalharga: " + totalharga);

    if (con != null) {
        datatable();
        hitungJumlahTotal();
    } else {
        System.err.println("Koneksi database gagal.");
    }

    
    menuBar = new JMenuBar(); 
    menu = new JMenu("Menu"); 
    
    JMenuItem menuItemstok_barang = new JMenuItem("Stok Barang");
        menuItemstok_barang.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); 
               new stok_barang().setVisible(true); 
            }
        });

JMenuItem menuItemFrom_Login = new JMenuItem("Logout");
menuItemFrom_Login.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent e) {
        dispose(); 
        new Login.From_Login().setVisible(true); 
    }
});

    JMenuItem menuItemcreate_user = new JMenuItem("Create User");
        menuItemcreate_user.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); 
               new create_user().setVisible(true); 
            }
        });

menu.add(menuItemcreate_user);
menu.add(menuItemstok_barang);
menu.add(menuItemFrom_Login);
menuBar.add(menu);
setJMenuBar(menuBar);


    }
    
    protected void datatable() {
    Object[] Baris = {"ID Transaksi", "Total Harga", "Uang Customer", "Kembalian"};
    tabmode = new DefaultTableModel(null, Baris);
    tb_invoice.setModel(tabmode); 

    String sql = "SELECT * FROM invoice ORDER BY id_transaksi ASC";
    try {
        Statement stat = con.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            String a = hasil.getString("id_transaksi");
            String b = hasil.getString("totalharga");
            String c = hasil.getString("uangcash");
            String d = hasil.getString("kembalian");

            String[] data = {a, b, c, d};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        System.err.println("Error datatable : " + e.getMessage());
    }
}
    
    protected void hitungJumlahTotal() {
    try {
        String sql = "SELECT SUM(totalharga) AS totalharga FROM invoice"; 
        Statement stat = con.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        if (hasil.next()) {
            int total = hasil.getInt("totalharga"); 
            totalharga.setText(String.valueOf(total));
        }
    } catch (Exception e) {
        System.err.println("Error hitung total: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_invoice = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("From Penghasilan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 11, 510, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Data Penjualan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 180, 30);

        tb_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_invoice);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 490, 92);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Total Pendapatan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 320, 180, 30);
        jPanel1.add(totalharga);
        totalharga.setBounds(210, 320, 285, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ChatGPT Image Jun 23, 2025, 10_07_25 PM.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-350, -30, 990, 1310);

        jMenu1.setText("Menu");

        jMenuItem1.setText("stok_barang");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("create_user");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penghasilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_invoice;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
